# Change these first
owner: ton-actions # Your GitHub username
repo: freeton-status # Your Github repository name

# Add your sites here
sites:
  - name: freeton.org
    url: https://freeton.org
  - name: Wiki
    url: https://freeton.wiki
  - name: Docs
    url: http://docs.ton.dev
    expectedStatusCodes:
      - 200
      - 406    
  - name: Forum
    url: https://forum.freeton.org
  - name: main.ton.dev
    url: http://main.ton.dev
  - name: net.ton.dev
    url: http://net.ton.dev
  - name: Ton Live
    url: https://ton.live/main    

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /freeton-status
  logoUrl: https://ton-manifest-dev.firebaseapp.com/assets/create.09f2308a21898c8d.png
  name: Free TON Status
  introTitle: "Free TON resources monitioring"
  introMessage: This is a status page which provide status of Free TON ecosystem
  navbar:
    - title: Status
      href: /freeton-status
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
