# Change these first
owner: ch1seL # Your GitHub username
repo: freeton-upptime # Your Github repository name

# Add your sites here
sites:
  - name: freeton.org
    url: https://freeton.org/
  - name: Wiki
    url: https://freeton.wiki
  - name: Docs
    url: http://docs.ton.dev

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://ton-manifest-dev.firebaseapp.com/assets/create.09f2308a21898c8d.png
  name: Free TON Status
  introTitle: "Free TON resources monitioring"
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
